server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daydream?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: 123
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
